POST http://localhost:3000/users/signup HTTP/1.1
content-type: application/json

{ 
 "firstName":"Noodle House",
 "lastName":"Cuisine", 
 "email":"ksgerges@mum.edu",
 "password":"123456"
 }
###
put http://localhost:3000/users/update HTTP/1.1
content-type: application/json

{ 
    "_id":"5dabe4135274f222e8f2cebf",
    "cards":[
     {
        "cardname": "new 111 ",
        "front": "front front front",
        "back": "back back back",
        "type": "text",
        "priority": "2",
        "hints": [{"hint": "easy"}]
     },
          {
        "cardname": "new 2222",
        "front": "front front front",
        "back": "back back back",
        "type": "text",
        "priority": "2",
        "hints": [{"hint": "easy"}]
     }
    ]
}

###
put http://localhost:3000/users/5dabe4135274f222e8f2cebf HTTP/1.1
content-type: application/json

{ 
    "cards":[
     {
        "cardname": "new 111 ",
        "front": "front front front",
        "back": "back back back",
        "type": "text",
        "priority": "2",
        "hints": [{"hint": "easy"}]
     },
          {
        "cardname": "new 2222",
        "front": "front front front",
        "back": "back back back",
        "type": "text",
        "priority": "2",
        "hints": [{"hint": "easy"}]
     }
    ]
}

###
POST http://localhost:3000/users/signup HTTP/1.1
content-type: application/json

{ 
 "firstName":"Test3 TEst",
 "lastName":"Cuisine", 
 "email":"ssksgerg55465es@mum.edu",
 "password":"123456"
 }


####
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{ 
 "email":"ssksgerg55465es@mum.edu",
 "password":"123456"
}


####
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{ 
 "email":"ssksgerg999es@mum.edu",
 "password":"1234566767"
}

#### 
GET http://localhost:3000/api/protected/users HTTP/1.1
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGFjMTI0NGEyMjJhYzMyNDBjZmFkZTciLCJpYXQiOjE1NzE1NTgxMjF9.vdnYzHVZYE0K2h6Id7ANSBPDPhXdDSCtb9yKfebUiLg

######
GET http://localhost:3000/api/protected/users HTTP/1.1
content-type: application/json


######
GET http://localhost:3000/users/5dabe4135274f222e8f2cebf HTTP/1.1
content-type: application/json


###
put http://localhost:3000/users/updatestatus HTTP/1.1
content-type: application/json

{ 
    "_id":"5dabe4135274f222e8f2cebf",
    "status" : "false"
}